### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by nyoravim** [HadrianFinch/ImageAsciifier#1]
Hi! I would love to learn about this and how it converts images to ASCII art, but I have no idea what's going on. How does this image processor work?

*(this is pretty cool)*
![image](https://user-images.githubusercontent.com/25918459/193957526-6528c375-74ab-4a05-8870-bc6efaac246a.png)

**Comment by TheLadyLuthien** [comment]
Fixed it! Here is a link to the documentation: [https://github.com/HadrianFinch/ImageAsciifier/wiki](url)
